### ISSUE TITLE
Could you share pretrained model?

### ISSUE THREAD

**Issue by kamata1729** [thancaocuong/pytorch-sspm#1]
I want to use this implementation model to some product, so could you upload your pretrained model?

**Comment by thancaocuong** [comment]
Hi @kamata1729, currently my implementation cannot obtain the desirable result (can not achive 68mAP on cocoval2017). But you can follow these instruction in README.md to train your own model

**Comment by thancaocuong** [comment]
Hi @kamata1729, I have only 14 keypoints pretrained model that I can share to you (I remove eyes , ears and add neck as average of left shoulder and right shoulder). So if you want I can share it to you.  this model obtain 29.7 mAP on 14 keypoints cocoval2017.

**Comment by thancaocuong** [comment]
@kamata1729 you can checkout [14_keypoints](https://github.com/thancaocuong/pytorch-sspm/tree/14_keypoints) branch, I publish my 30mAP pretrained model.  Hope It could help your works.
